### PR TITLE
Extend API call patch_device_type() to patch_device_model()

### LINKED ISSUE #109: Patch device API with new Supervisor version for balenaOS to balenaOS migration
Takeover does not update the device API with the new Supervisor version as it should. This omission may result in the Supervisor crash-looping after takeover due to a failed database migration, like below.
```
Mar 11 16:16:45 c956900 62f5d331249c[2052]: [info]    Supervisor v16.6.1 starting up...
Mar 11 16:16:45 c956900 62f5d331249c[2052]: [error]   Uncaught exception: Error: The migration directory is corrupt, the following files are missing: M00012.js
Mar 11 16:16:45 c956900 62f5d331249c[2052]: [error]         at validateMigrationList (/usr/src/app/dist/app.js:2:2023510)
Mar 11 16:16:45 c956900 62f5d331249c[2052]: [error]       at Migrator.latest (/usr/src/app/dist/app.js:2:2024717)
Mar 11 16:16:45 c956900 62f5d331249c[2052]: [error]       at async Supervisor.init (/usr/src/app/dist/app.js:10:168834)
```

Takeover must update the device API like balenahup does [here](https://github.com/balena-os/balenahup/blob/dbdfe0b30da20c9c68fca47e0961c6ec0aab6e88/upgrade-2.x.sh#L299).

### PR DESCRIPTION
**Pull request by kb2ma**
Call whenever config.json indicates a balenaOS device, by presence of UUID.

* Null out values for current OS version and pinned version
* Null out values for current Supervisor version and pinned version
* Allow device type change to be optional

Change-type: patch

Fixes #109 

Clearing the OS and Supervisor versions works well for coordination with the back end, since takeover usually is an abrupt change to the device. Due to #109 clearing the Supervisor versions actually is required.

-----

Tested these takeovers:
* balenaOS raspberrypi3 -> raspberrypi3-64
* Debian 11 -> balenaOS intel-nuc
* balenaOS intel-nuc -> generic-amd64

### CODE REVIEW

**Comment by kb2ma** [comment]
As a follow-on PR, I think it would work better to lookup the target device type ID from the API when initializing MigrateInfo -- rather than in `patch_device_model()`. We don't want to find a mistake just before reboot.

File: src/common/api_calls.rs [hunk 1]
```diff
@@ -192,92 +192,106 @@ pub(crate) fn get_os_image(
...
-    dt_slug: &str,
     uuid: &str,
+    dt_slug: &Option<String>,
 ) -> Result<()> {
     let headers = get_header(api_key)?;
 
-    // Before we can patch the deviceType, we need to get the deviceId corresponding to the slug
-    let dt_id_request_url = get_device_type_info_url(api_endpoint, "id", dt_slug);
+    // To set device type, we first must retrieve the ID corresponding to the slug.
+    let mut dt_id = 0_u32; // using type of DeviceTypeIdApiResponse.id
```
Comment (pipex) [inline src/common/api_calls.rs]: I think it would be a bit more idiomatic to use `Option<u32>` here

File: src/common/api_calls.rs [hunk 2]
```diff
@@ -192,92 +192,106 @@ pub(crate) fn get_os_image(
...
+
+    values.insert("os_version".to_string(), json!(null));
+    values.insert("should_be_operated_by__release".to_string(), json!(null));
+    values.insert("supervisor_version".to_string(), json!(null));
+    values.insert("should_be_managed_by__release".to_string(), json!(null));
+    if dt_id > 0 {
+        values.insert("is_of__device_type".to_string(), json!(dt_id));
+    }
+
+    let patch_res = Client::builder()
```
Comment (pipex) [inline src/common/api_calls.rs]: I think you can re-use the previous Client to avoid initializing twice

**Review by pipex — COMMENTED** [review]
Overall just a few nits

File: src/common/api_calls.rs [hunk 3]
```diff
@@ -192,94 +192,104 @@ pub(crate) fn get_os_image(
...
+    // PATCH device model
+    let patch_url = format!("{api_endpoint}/v7/device(uuid='{uuid}')");
+    let mut values = serde_json::Map::new();
+
+    values.insert("os_version".to_string(), json!(null));
+    values.insert("should_be_operated_by__release".to_string(), json!(null));
+    values.insert("supervisor_version".to_string(), json!(null));
+    values.insert("should_be_managed_by__release".to_string(), json!(null));
+    if dt_id.is_some() {
+        values.insert("is_of__device_type".to_string(), json!(Some(dt_id)));
```
[the remark this answers is not in the document]
Comment (kb2ma) [reply src/common/api_calls.rs]: Fixed; thanks for finding. Sometimes the syntax trips me up. I understand it better now.

Yes, tested. It looks like the `json` macro recurses down to a primitive value. Here is output from a little experiment:
```
count = 17
JSON count = 17
some_count = Some(17)
JSON some_count = 17
some_some_count = Some(Some(17))
JSON some_some_count = 17
```

**Review by pipex — APPROVED** [review]
